# Generated by Django 5.0.1 on 2024-02-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_publicacao_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='publicacao_id',
            new_name='publicacao',
        ),
    ]
